// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package types_test

import (
	"golang.org/x/tools/go/packages"
)

type mockGoDir struct {
	PathCalled chan bool
	PathOutput struct {
		Path chan string
	}
	PackageCalled chan bool
	PackageOutput struct {
		Pkg chan *packages.Package
	}
	ImportCalled chan bool
	ImportInput  struct {
		Path chan string
	}
	ImportOutput struct {
		Pkg chan *packages.Package
		Err chan error
	}
}

func newMockGoDir() *mockGoDir {
	m := &mockGoDir{}
	m.PathCalled = make(chan bool, 100)
	m.PathOutput.Path = make(chan string, 100)
	m.PackageCalled = make(chan bool, 100)
	m.PackageOutput.Pkg = make(chan *packages.Package, 100)
	m.ImportCalled = make(chan bool, 100)
	m.ImportInput.Path = make(chan string, 100)
	m.ImportOutput.Pkg = make(chan *packages.Package, 100)
	m.ImportOutput.Err = make(chan error, 100)
	return m
}
func (m *mockGoDir) Path() (path string) {
	m.PathCalled <- true
	return <-m.PathOutput.Path
}
func (m *mockGoDir) Package() (pkg *packages.Package) {
	m.PackageCalled <- true
	return <-m.PackageOutput.Pkg
}
func (m *mockGoDir) Import(path string) (pkg *packages.Package, err error) {
	m.ImportCalled <- true
	m.ImportInput.Path <- path
	return <-m.ImportOutput.Pkg, <-m.ImportOutput.Err
}
