// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package mocks_test

import "go/ast"

type mockTypeFinder struct {
	ExportedTypesCalled chan bool
	ExportedTypesOutput struct {
		Ret0 chan []*ast.TypeSpec
	}
}

func newMockTypeFinder() *mockTypeFinder {
	m := &mockTypeFinder{}
	m.ExportedTypesCalled = make(chan bool, 100)
	m.ExportedTypesOutput.Ret0 = make(chan []*ast.TypeSpec, 100)
	return m
}
func (m *mockTypeFinder) ExportedTypes() []*ast.TypeSpec {
	m.ExportedTypesCalled <- true
	return <-m.ExportedTypesOutput.Ret0
}
